name: smartpillbox_alarm
description: smartpillbox_alarm demonstrates how to use the alarm plugin, sample from alarm_example
version: 0.1.2

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  alarm: 
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  logging: ^1.3.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  http: 
  gsheets: 
  background_fetch: 
  intl: 
  shared_preferences: 


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/mozart.mp3
    - assets/nokia.mp3
    - assets/one_piece.mp3
    - assets/star_wars.mp3
    - assets/marimba.mp3
